"use client";

import { ArrowLeft, Save, X, Eye, ChevronRight, AlertCircle, Camera, Tag, FileText, History, Wrench, Image as ImageIcon, Banknote, Lock, Sparkles } from "lucide-react";
import Link from "next/link";
import { useState, useRef, useEffect } from "react";
import { createPortal } from "react-dom";
import { updateMotor } from "@/lib/actions";
import { getBranches } from "@/lib/branch-actions";
import { useFormStatus } from "react-dom";
import SmartInspectionTabClient from "./SmartInspectionTabClient";

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <button 
      type="submit"
      disabled={pending}
      className="px-6 py-2.5 rounded-lg bg-[var(--primary)] text-white font-medium hover:bg-[var(--primary)]/90 transition-colors flex items-center gap-2 disabled:opacity-70"
    >
      <Save size={18} />
      {pending ? "Menyimpan..." : "Simpan Perubahan"}
    </button>
  );
}

const TABS = [
  { id: 1, name: "Identitas Unit", icon: <Tag size={18} /> },
  { id: 2, name: "Pajak & Dokumen", icon: <FileText size={18} /> },
  { id: 3, name: "Riwayat Unit", icon: <History size={18} /> },
  { id: 4, name: "Inspeksi & Kondisi", icon: <Wrench size={18} /> },
  { id: 5, name: "Foto & Video", icon: <ImageIcon size={18} /> },
  { id: 6, name: "Harga & Pembayaran", icon: <Banknote size={18} /> },
  { id: 7, name: "Data Internal", icon: <Lock size={18} /> },
];

export default function EditMotorClient({ motor, userRole = "ADMIN" }: { motor: any, userRole?: string }) {
  const [activeTab, setActiveTab] = useState(1);
  
  // Filter tabs based on role
  const visibleTabs = TABS.filter(tab => {
    if (userRole === "MECHANIC") return tab.id === 4; // Mechanic only sees Tab 4
    return true; // Admin and Supervisor see all tabs
  });

  const [previews, setPreviews] = useState<string[]>([
    motor.image || "", 
    motor.images?.[0] || "", 
    motor.images?.[1] || "", 
    motor.images?.[2] || "",
    motor.images?.[3] || "",
    motor.images?.[4] || "",
  ]);
  const fileInputRefs = useRef<(HTMLInputElement | null)[]>([]);
  const formRef = useRef<HTMLFormElement>(null);
  const [showImageError, setShowImageError] = useState(false);
  const [isMounted, setIsMounted] = useState(false);
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [branches, setBranches] = useState<any[]>([]);
  const [descriptionText, setDescriptionText] = useState(motor.description || "");

  const handleAutoGenerateDescription = () => {
    if (!formRef.current) return;
    const formData = new FormData(formRef.current);
    
    const brand = formData.get("brand") || motor.brand || "";
    const name = formData.get("name") || motor.name || "";
    const variant = formData.get("variant") || motor.variant || "";
    const year = formData.get("year") || motor.year || "";
    const color = formData.get("color") || motor.color || "";
    const odo = formData.get("odo") || motor.odo || "";
    const taxStatus = formData.get("tax_status") || motor.tax_status || "Hidup";
    const priceCash = formData.get("price") || motor.price || "";
    const dp = formData.get("min_dp") || motor.min_dp || "";

    const fullName = `${brand} ${name} ${variant} ${year}`.replace(/\s+/g, ' ').trim();
    
    let text = `Dijual ${fullName || "unit motor bekas berkualitas"}`;
    if (color) text += ` warna ${color}`;
    text += `.`;

    if (odo) text += ` Odometer baru ${Number(odo).toLocaleString("id-ID")} KM`;
    if (taxStatus) text += `, status pajak ${String(taxStatus).toLowerCase()}`;
    text += `. Kondisi mesin halus, kelistrikan normal, dan siap pakai.`;

    if (priceCash) {
      const formattedPrice = Number(priceCash).toLocaleString("id-ID");
      text += ` Harga Cash Rp ${formattedPrice}`;
      if (dp) {
        const formattedDp = Number(dp).toLocaleString("id-ID");
        text += ` atau Kredit DP minim mulai Rp ${formattedDp}`;
      }
      text += `.`;
    }

    text += ` Surat-surat terjamin keabsahannya. Garansi mesin & layanan pasca jual di Timbul Motor Kebumen!`;

    setDescriptionText(text);
  };

  useEffect(() => {
    setIsMounted(true);
    getBranches().then(setBranches);
    
    // Check URL params for initial tab
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      const tabParam = params.get('tab');
      if (tabParam) {
        setActiveTab(parseInt(tabParam, 10));
      } else if (userRole === "MECHANIC") {
        setActiveTab(4); // Default to tab 4 for mechanic
      }
    }
  }, [userRole]);

  const draftKey = `editMotorDraftV2_${motor.id}`;

  useEffect(() => {
    const draft = localStorage.getItem(draftKey);
    if (draft && formRef.current) {
      try {
        const data = JSON.parse(draft);
        Object.entries(data).forEach(([key, value]) => {
          if (['km', 'price', 'dp_min', 'purchase_price', 'recondition_cost', 'credit_price', 'monthly_install'].includes(key)) {
            const el = document.getElementsByName(key)[0] as HTMLInputElement;
            if (el) el.value = value as string;
          }

          const input = formRef.current?.elements.namedItem(key);
          if (input) {
            if (input instanceof RadioNodeList) {
              input.value = value as string;
            } else if (input instanceof HTMLInputElement && (input.type === 'checkbox' || input.type === 'radio')) {
              if (input.value === value) input.checked = true;
            } else {
              (input as any).value = value;
            }
          }
        });
      } catch (e) {
        console.error("Failed to load draft", e);
      }
    }
  }, [draftKey]);

  const handleFormChange = () => {
    if (!formRef.current) return;
    const formData = new FormData(formRef.current);
    const data = Object.fromEntries(formData.entries());
    for (let i = 0; i < 15; i++) delete data[`image_${i}`];
    localStorage.setItem(draftKey, JSON.stringify(data));
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>, index: number) => {
    const file = e.target.files?.[0];
    if (file) {
      const img = new Image();
      const objectUrl = URL.createObjectURL(file);
      
      img.onload = () => {
        const canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext("2d");
        
        if (ctx) {
          ctx.drawImage(img, 0, 0);
          
          const text = "TIMBUL MOTOR";
          ctx.translate(img.width / 2, img.height / 2);
          const angle = Math.atan2(-img.height, img.width);
          ctx.rotate(angle);
          
          let fontSize = 100; 
          ctx.font = `bold ${fontSize}px Arial`;
          let textWidth = ctx.measureText(text).width;
          const diagonal = Math.sqrt(img.width * img.width + img.height * img.height);
          const maxTextWidth = diagonal * 0.8;
          fontSize = fontSize * (maxTextWidth / textWidth);
          ctx.font = `bold ${fontSize}px Arial`;
          ctx.fillStyle = "rgba(255, 255, 255, 0.25)"; 
          ctx.textAlign = "center";
          ctx.textBaseline = "middle";
          ctx.shadowColor = "rgba(0, 0, 0, 0.5)";
          ctx.shadowBlur = 10;
          ctx.shadowOffsetX = 2;
          ctx.shadowOffsetY = 2;
          ctx.fillText(text, 0, 0);
          ctx.rotate(-angle);
          ctx.translate(-img.width / 2, -img.height / 2);
          
          canvas.toBlob((blob) => {
            if (blob) {
              const watermarkedFile = new File([blob], file.name, { type: "image/jpeg" });
              const dt = new DataTransfer();
              dt.items.add(watermarkedFile);
              
              if (fileInputRefs.current[index]) {
                fileInputRefs.current[index]!.files = dt.files;
              }
              
              const watermarkedUrl = URL.createObjectURL(watermarkedFile);
              setPreviews(prev => {
                const next = [...prev];
                next[index] = watermarkedUrl;
                return next;
              });
            }
          }, "image/jpeg", 0.9);
        }
        URL.revokeObjectURL(objectUrl);
      };
      img.src = objectUrl;
    }
  };

  const removeImage = (e: React.MouseEvent, index: number) => {
    e.stopPropagation();
    const newPreviews = [...previews];
    newPreviews[index] = "";
    setPreviews(newPreviews);
    if (fileInputRefs.current[index]) {
      fileInputRefs.current[index]!.value = "";
    }
  };

  const handleNumberFormat = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/\D/g, "");
    e.target.value = value ? Number(value).toLocaleString("id-ID") : "";
    handleFormChange(); 
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    if (!previews[0]) {
      e.preventDefault();
      setShowImageError(true);
      return;
    }
    localStorage.removeItem(draftKey);
  };

  const handleInvalid = (e: React.FormEvent<HTMLFormElement>) => {
    const target = e.target as HTMLElement;
    const tabContainer = target.closest('[data-tab]');
    if (tabContainer) {
      const tabId = parseInt(tabContainer.getAttribute('data-tab') || '1', 10);
      setActiveTab(tabId);
    }
  };

  const imageLabels = ["Foto Utama", "Samping Kiri", "Samping Kanan", "Mesin Kiri", "Mesin Kanan", "Speedometer"];
  const updateMotorWithId = updateMotor.bind(null, motor.id);

  return (
    <div className="max-w-6xl mx-auto flex flex-col gap-6 pb-24 relative">
      {showImageError && isMounted && createPortal(
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-sm overflow-hidden animate-in fade-in duration-200">
            <div className="bg-red-50 p-4 flex items-center justify-center">
              <AlertCircle size={48} className="text-red-500" />
            </div>
            <div className="p-6 text-center space-y-3">
              <h3 className="text-lg font-bold text-[var(--foreground)]">Foto Utama Kosong!</h3>
              <p className="text-sm text-[var(--muted-foreground)]">
                Anda wajib mengunggah setidaknya 1 buah <strong>Foto Utama</strong> di Tab 5 sebelum menyimpan.
              </p>
            </div>
            <div className="p-4 bg-[var(--muted)]/50 border-t border-[var(--border)]">
              <button 
                onClick={() => setShowImageError(false)}
                className="w-full py-2.5 bg-[var(--primary)] text-white font-semibold rounded-lg hover:bg-[var(--primary)]/90 transition-colors"
              >
                Mengerti
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}

      <div className="flex items-center gap-4 bg-white p-4 rounded-xl border border-[var(--border)] shadow-sm">
        <Link href="/admin/inventory" className="p-2 hover:bg-[var(--muted)] rounded-lg transition-colors text-[var(--muted-foreground)]">
          <ArrowLeft size={20} />
        </Link>
        <div>
          <h1 className="text-xl font-bold text-[var(--foreground)]">Edit Motor: {motor.name}</h1>
          <p className="text-xs text-[var(--muted-foreground)]">Kode Unit: {motor.code}</p>
        </div>
      </div>

      <div className="flex flex-col md:flex-row gap-6 items-start">
        <div className="md:w-64 flex-shrink-0">
          <div className="bg-white rounded-xl border border-[var(--border)] shadow-sm overflow-hidden sticky top-8">
            <div className="p-3 bg-[var(--muted)]/50 border-b border-[var(--border)] font-semibold text-sm text-[var(--foreground)]">Navigasi Form</div>
            <div className="flex flex-col">
              {visibleTabs.map((tab) => (
                <button
                  type="button"
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-3 px-4 py-3 text-sm font-medium transition-colors border-l-4 ${
                    activeTab === tab.id 
                      ? "border-[var(--primary)] bg-[var(--primary)]/5 text-[var(--primary)]" 
                      : "border-transparent text-[var(--muted-foreground)] hover:bg-[var(--muted)]/50 hover:text-[var(--foreground)]"
                  }`}
                >
                  <span className="flex-shrink-0">{tab.icon}</span>
                  {tab.name}
                  {activeTab === tab.id && <ChevronRight size={16} className="ml-auto" />}
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="flex-1">
          <form 
            ref={formRef}
            onChange={handleFormChange}
            onSubmit={handleSubmit}
            onInvalid={handleInvalid}
            className="space-y-6" 
            action={updateMotorWithId}
          >
            <div data-tab="1" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 1 && "hidden"}`}>
              <h2 className="font-bold text-lg border-b border-[var(--border)] pb-2 flex items-center gap-2">
                <Tag className="text-[var(--primary)]" size={20} /> Tab 1: Identitas & Spesifikasi Unit
              </h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-sm font-medium">Merek <span className="text-red-500">*</span></label>
                  <select name="brand" defaultValue={motor.brand} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="">Pilih Merek</option>
                    <option value="Honda">Honda</option>
                    <option value="Yamaha">Yamaha</option>
                    <option value="Suzuki">Suzuki</option>
                    <option value="Kawasaki">Kawasaki</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Kategori <span className="text-red-500">*</span></label>
                  <select name="type" defaultValue={motor.type} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="">Pilih Kategori</option>
                    <option value="matic">Matic</option>
                    <option value="bebek">Bebek</option>
                    <option value="sport">Sport</option>
                    <option value="trail">Trail/Cross</option>
                    <option value="cruiser">Cruiser</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Nama / Seri Lengkap <span className="text-red-500">*</span></label>
                  <input type="text" name="name" defaultValue={motor.name} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Varian / Trim <span className="text-xs text-gray-500 font-normal">(Opsional)</span></label>
                  <input type="text" name="variant" defaultValue={motor.variant || ""} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Kapasitas Mesin (cc) <span className="text-red-500">*</span></label>
                  <input type="number" name="cc" defaultValue={motor.cc} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Transmisi <span className="text-red-500">*</span></label>
                  <select name="transmission" defaultValue={motor.transmission} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Automatic">Automatic (CVT)</option>
                    <option value="Manual">Manual</option>
                    <option value="Semi-Automatic">Semi-Automatic</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Sistem Bahan Bakar</label>
                  <select name="fuel_system" defaultValue={motor.fuel_system || "Injeksi"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Injeksi">Injeksi (FI)</option>
                    <option value="Karburator">Karburator</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Tahun Pembuatan <span className="text-red-500">*</span></label>
                  <input type="number" name="year" defaultValue={motor.year} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Warna Asli <span className="text-red-500">*</span></label>
                  <input type="text" name="color" defaultValue={motor.color} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Kilometer (Odo) <span className="text-red-500">*</span></label>
                  <input type="text" name="km" defaultValue={motor.km.toLocaleString("id-ID")} required onChange={handleNumberFormat} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Lokasi Unit <span className="text-red-500">*</span></label>
                  <select name="location" defaultValue={motor.location || "Showroom Utama Kebumen"} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    {branches.length > 0 ? branches.map(b => (
                      <option key={b.id} value={b.name}>{b.name}</option>
                    )) : (
                      <>
                        <option value="Showroom Utama Kebumen">Showroom Utama Kebumen</option>
                        <option value="Cabang Gombong">Cabang Gombong</option>
                      </>
                    )}
                  </select>
                </div>
              </div>
            </div>

            <div data-tab="2" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 2 && "hidden"}`}>
              <h2 className="font-bold text-lg border-b border-[var(--border)] pb-2 flex items-center gap-2">
                <FileText className="text-[var(--primary)]" size={20} /> Tab 2: Legalitas & Dokumen
              </h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-sm font-medium">Nomor Polisi (Plat) <span className="text-xs text-red-500">(Internal)</span></label>
                  <input type="text" name="plate_number" defaultValue={motor.plate_number || ""} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Wilayah Registrasi</label>
                  <input type="text" name="plate_area" defaultValue={motor.plate_area || ""} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Status Pajak Tahunan <span className="text-red-500">*</span></label>
                  <select name="tax_status" defaultValue={motor.tax_status} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Hidup">Hidup (Aktif)</option>
                    <option value="Mati">Mati (Kadaluarsa)</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Jatuh Tempo Pajak <span className="text-red-500">*</span></label>
                  <input type="date" name="tax_expiry" defaultValue={motor.tax_expiry} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Masa Berlaku STNK (Plat 5 Thn)</label>
                  <input type="date" name="stnk_expiry" defaultValue={motor.stnk_expiry || ""} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                
                <div className="col-span-2 border-t border-[var(--border)] my-2"></div>
                
                <div className="space-y-1">
                  <label className="text-sm font-medium">Status STNK</label>
                  <select name="stnk_status" defaultValue={motor.stnk_status || "Ada, asli, dan terverifikasi"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Ada, asli, dan terverifikasi">Ada, asli, terverifikasi</option>
                    <option value="Ada, belum diverifikasi">Ada, belum diverifikasi</option>
                    <option value="Proses Perpanjangan">Proses Perpanjangan</option>
                    <option value="Hilang">Hilang</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Status BPKB</label>
                  <select name="bpkb_status" defaultValue={motor.bpkb_status || "Ada, asli, dan terverifikasi"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Ada, asli, dan terverifikasi">Ada, asli, terverifikasi</option>
                    <option value="Sekolah / Dijaminkan">Sekolah / Dijaminkan (Butuh Pelunasan)</option>
                    <option value="Proses Balik Nama">Proses Balik Nama</option>
                    <option value="Tidak Tersedia">Tidak Tersedia</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Kesesuaian Nomor Rangka</label>
                  <select name="chassis_match" defaultValue={motor.chassis_match || "Sesuai"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Sesuai">Sesuai Dokumen</option>
                    <option value="Tidak Sesuai">Tidak Sesuai</option>
                    <option value="Belum Diperiksa">Belum Diperiksa</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Kesesuaian Nomor Mesin</label>
                  <select name="engine_match" defaultValue={motor.engine_match || "Sesuai"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Sesuai">Sesuai Dokumen</option>
                    <option value="Tidak Sesuai">Tidak Sesuai</option>
                    <option value="Belum Diperiksa">Belum Diperiksa</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">KTP Pemilik Sebelumnya</label>
                  <select name="ktp_owner" defaultValue={motor.ktp_owner || "Tersedia"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Tersedia">Tersedia (Bisa pinjam KTP)</option>
                    <option value="Tidak Tersedia">Tidak Tersedia (Wajib BBN)</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Faktur Kendaraan</label>
                  <select name="faktur" defaultValue={motor.faktur || "Ada"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Ada">Ada</option>
                    <option value="Tidak Ada">Tidak Ada</option>
                  </select>
                </div>
                
                <div className="col-span-2 p-3 bg-red-50 border border-red-100 rounded-lg space-y-2">
                  <p className="text-xs font-bold text-red-800 flex items-center gap-1.5"><AlertCircle size={14} /> Data Internal Rahasia (TIDAK DITAMPILKAN DI PUBLIK)</p>
                  <div className="grid grid-cols-2 gap-4">
                    <input type="text" name="chassis_number" defaultValue={motor.chassis_number || ""} placeholder="Nomor Rangka Lengkap" className="w-full px-3 py-2 rounded-lg border border-red-200 focus:outline-none focus:border-red-400 text-sm bg-white" />
                    <input type="text" name="engine_number" defaultValue={motor.engine_number || ""} placeholder="Nomor Mesin Lengkap" className="w-full px-3 py-2 rounded-lg border border-red-200 focus:outline-none focus:border-red-400 text-sm bg-white" />
                  </div>
                </div>
              </div>
            </div>

            <div data-tab="3" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 3 && "hidden"}`}>
              <h2 className="font-bold text-lg border-b border-[var(--border)] pb-2 flex items-center gap-2">
                <History className="text-[var(--primary)]" size={20} /> Tab 3: Riwayat Kendaraan
              </h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-sm font-medium">Jumlah Pemilik Sebelumnya</label>
                  <select name="previous_owners" defaultValue={motor.previous_owners || "Tangan Pertama"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Tangan Pertama">Tangan Pertama</option>
                    <option value="Tangan Kedua">Tangan Kedua</option>
                    <option value="Lebih dari dua">Lebih dari dua</option>
                    <option value="Tidak Diketahui">Tidak Diketahui</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Penggunaan Sebelumnya</label>
                  <select name="usage_type" defaultValue={motor.usage_type || "Pribadi / Harian"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Pribadi / Harian">Pribadi / Harian</option>
                    <option value="Ojek Online">Ojek Online (Ojol)</option>
                    <option value="Operasional Perusahaan">Operasional Perusahaan</option>
                    <option value="Tidak Diketahui">Tidak Diketahui</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Riwayat Kecelakaan / Jatuh</label>
                  <select name="crash_history" defaultValue={motor.crash_history || "Bebas Tabrak / Jatuh"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Bebas Tabrak / Jatuh">Bebas Tabrak / Jatuh (Aman)</option>
                    <option value="Pernah Jatuh Ringan">Pernah Jatuh Ringan (Lecet/Spion Patah)</option>
                    <option value="Pernah Tabrakan Berat">Tabrakan Berat (Ganti Rangka dll)</option>
                    <option value="Tidak Diketahui">Tidak Diketahui</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Riwayat Banjir</label>
                  <select name="flood_history" defaultValue={motor.flood_history || "Bebas Banjir"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Bebas Banjir">Bebas Banjir</option>
                    <option value="Pernah Terendam">Pernah Terendam</option>
                    <option value="Tidak Diketahui">Tidak Diketahui</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Riwayat Turun Mesin / Bore Up</label>
                  <select name="engine_rebuild" defaultValue={motor.engine_rebuild || "Standar Pabrik (Segel)"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Standar Pabrik (Segel)">Standar Pabrik (Belum pernah bongkar)</option>
                    <option value="Pernah Servis Besar">Pernah Servis Besar</option>
                    <option value="Modifikasi / Bore Up">Modifikasi / Bore Up</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Status Odometer (KM)</label>
                  <select name="odo_status" defaultValue={motor.odo_status || "Asli (Terverifikasi)"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="Asli (Terverifikasi)">Asli (Sesuai histori servis)</option>
                    <option value="Indikasi Riset/Putaran">Indikasi Riset / Tidak Wajar</option>
                    <option value="Mati / Rusak">Speedometer Rusak</option>
                  </select>
                </div>
              </div>
            </div>

            <div data-tab="4" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 4 && "hidden"}`}>
              <SmartInspectionTabClient motorId={motor.id} userRole={userRole} isReadOnly={!["MECHANIC", "ADMIN", "SUPER_ADMIN"].includes(userRole)} />
            </div>

            <div data-tab="5" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 5 && "hidden"}`}>
              <h2 className="font-bold text-lg border-b border-[var(--border)] pb-2 flex items-center justify-between">
                <span className="flex items-center gap-2"><ImageIcon className="text-[var(--primary)]" size={20} /> Tab 5: Galeri & Video</span>
                <span className="text-xs font-normal text-blue-600 bg-blue-50 px-2 py-1 rounded">Auto-Watermark</span>
              </h2>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                {previews.map((preview, index) => (
                  <div key={index} className="space-y-2">
                    <div 
                      className={`aspect-square rounded-xl border-2 border-dashed flex flex-col items-center justify-center relative overflow-hidden cursor-pointer transition-colors ${preview ? 'border-[var(--primary)]' : 'border-[var(--border)] hover:border-[var(--primary)] hover:bg-[var(--primary)]/5'}`}
                      onClick={() => fileInputRefs.current[index]?.click()}
                    >
                      {preview ? (
                        <>
                          <img src={preview} alt={`Preview ${index + 1}`} className="w-full h-full object-cover" />
                          <div className="absolute top-2 right-2 flex gap-1">
                            <button type="button" onClick={(e) => { e.stopPropagation(); setSelectedImage(preview); }} className="p-1.5 bg-blue-500 text-white rounded-full hover:bg-blue-600 shadow-sm"><Eye size={14} /></button>
                            <button type="button" onClick={(e) => removeImage(e, index)} className="p-1.5 bg-red-500 text-white rounded-full hover:bg-red-600 shadow-sm"><X size={14} /></button>
                          </div>
                        </>
                      ) : (
                        <>
                          <Camera className="text-[var(--muted-foreground)] mb-2" size={24} />
                          <span className="text-xs text-[var(--muted-foreground)] text-center px-2">Upload {imageLabels[index]}</span>
                        </>
                      )}
                      <input 
                        type="file" accept="image/*" name={`image_${index}`} className="hidden" 
                        ref={(el) => { if (el) fileInputRefs.current[index] = el; }}
                        onChange={(e) => handleImageUpload(e, index)}
                      />
                      <input type="hidden" name={`existing_image_${index}`} value={preview || ""} />
                    </div>
                    <div className="text-center">
                      <span className="text-xs font-bold text-gray-700 bg-gray-100 px-2 py-1 rounded-full">{imageLabels[index] || `Foto ${index+1}`}</span>
                    </div>
                  </div>
                ))}
              </div>
              
              <div className="space-y-2 sm:col-span-2 mt-4 pt-4 border-t border-[var(--border)]">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <label className="text-sm font-bold text-[var(--foreground)]">Deskripsi Promosi Kendaraan</label>
                  <button 
                    type="button"
                    onClick={handleAutoGenerateDescription}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-purple-50 hover:bg-purple-100 text-purple-700 text-xs font-semibold rounded-lg border border-purple-200 transition-colors shadow-sm cursor-pointer"
                  >
                    <Sparkles size={14} className="text-purple-600" /> ✨ Buat Deskripsi Otomatis (1-Klik)
                  </button>
                </div>
                <textarea 
                  name="description" 
                  value={descriptionText}
                  onChange={(e) => setDescriptionText(e.target.value)}
                  rows={4} 
                  placeholder="Klik tombol 'Buat Deskripsi Otomatis' di atas untuk membuat kata-kata promosi secara instan..." 
                  className="w-full px-3.5 py-2.5 rounded-xl border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm leading-relaxed"
                />
                <p className="text-xs text-[var(--muted-foreground)]">
                  * Deskripsi ini akan ditampilkan di halaman detail stok publik untuk menarik minat calon pembeli.
                </p>
              </div>
              
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1">
                  Link Video Walkaround (Opsional)
                </label>
                <div className="relative">
                  <input type="url" name="videoUrl" defaultValue={motor.videoUrl || ""} placeholder="https://www.youtube.com/watch?v=..." className="w-full pl-3 pr-3 py-2 border border-[var(--border)] rounded-lg focus:ring-2 focus:ring-[var(--primary)] outline-none text-sm" />
                </div>
              </div>
            </div>

            <div data-tab="6" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 6 && "hidden"}`}>
              <h2 className="font-bold text-lg border-b border-[var(--border)] pb-2 flex items-center gap-2">
                <Banknote className="text-[var(--primary)]" size={20} /> Tab 6: Penjualan & Skema Kredit
              </h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-sm font-medium">Status Publikasi Unit <span className="text-red-500">*</span></label>
                  <select name="status" defaultValue={motor.status} required className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white dark:bg-[var(--background)]">
                    <option value="Draft">Draft (Disembunyikan)</option>
                    <option value="Tersedia">Tersedia (Dijual Publik)</option>
                    <option value="Sedang Dipesan">Sedang di-Booking (DP)</option>
                    <option value="Terjual">Terjual / Laku</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Bisa Tukar Tambah?</label>
                  <select name="trade_in_avail" defaultValue={motor.trade_in_avail ? "true" : "false"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="true">Ya, Menerima Tukar Tambah</option>
                    <option value="false">Tidak, Hanya Jual</option>
                  </select>
                </div>

                <div className="col-span-2 border-t border-[var(--border)] my-2"></div>
                <div className="col-span-2"><h3 className="font-bold text-gray-700">Skema Harga & Kredit</h3></div>

                <div className="space-y-1">
                  <label className="text-sm font-medium">Harga Cash (Tunai) <span className="text-red-500">*</span></label>
                  <input type="text" name="price" defaultValue={motor.price?.toLocaleString("id-ID") || ""} required onChange={handleNumberFormat} className="w-full px-3 py-2 font-bold rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Bisa Nego Harga Cash?</label>
                  <select name="is_nego" defaultValue={motor.is_nego ? "true" : "false"} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm bg-white">
                    <option value="true">Bisa Nego di Tempat</option>
                    <option value="false">Harga Pas (Nett)</option>
                  </select>
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Harga Kredit (Jika berbeda)</label>
                  <input type="text" name="credit_price" defaultValue={motor.credit_price?.toLocaleString("id-ID") || ""} onChange={handleNumberFormat} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Minimal DP (Rp) <span className="text-red-500">*</span></label>
                  <input type="text" name="dp_min" defaultValue={motor.dp_min?.toLocaleString("id-ID") || ""} required onChange={handleNumberFormat} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Estimasi Cicilan Termurah</label>
                  <input type="text" name="monthly_install" defaultValue={motor.monthly_install?.toLocaleString("id-ID") || ""} onChange={handleNumberFormat} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Pilihan Tenor Kredit <span className="text-xs text-gray-500 font-normal">(Bulan)</span></label>
                  <input type="text" name="tenor_options" defaultValue={motor.tenor_options || ""} pattern="^[0-9,\s]+$" title="Masukkan hanya angka dan koma, contoh: 11, 23, 35" placeholder="Cth: 11, 23, 35 (hanya angka & koma)" className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
              </div>
            </div>

            {/* Tab 7: Internal */}
            <div data-tab="7" className={`bg-white p-6 rounded-xl border border-[var(--border)] shadow-sm space-y-6 ${activeTab !== 7 && "hidden"}`}>
              <h2 className="font-bold text-lg border-b border-[var(--border)] pb-2 flex items-center gap-2">
                <Lock className="text-[var(--primary)]" size={20} /> Tab 7: Data Internal Dealer
              </h2>
              <div className="p-3 bg-red-50 border border-red-100 rounded-lg flex items-start gap-2">
                <AlertCircle className="text-red-600 mt-0.5 flex-shrink-0" size={16} />
                <p className="text-xs font-medium text-red-800">
                  Peringatan: Seluruh data di tab ini bersifat sangat RAHASIA dan tidak akan pernah ditampilkan ke publik / pembeli. Hanya digunakan untuk menghitung estimasi profit dealer.
                </p>
              </div>
              
              <div className="grid sm:grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-sm font-medium">Harga Modal Beli / Akuisisi</label>
                  <input type="text" name="purchase_price" defaultValue={motor.purchase_price?.toLocaleString("id-ID") || ""} onChange={handleNumberFormat} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Biaya Rekondisi / Servis / Detailing</label>
                  <input type="text" name="recondition_cost" defaultValue={motor.recondition_cost?.toLocaleString("id-ID") || ""} onChange={handleNumberFormat} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Nama & Kontak Supplier / Pemilik Lama</label>
                  <input type="text" name="supplier_name" defaultValue={motor.supplier_name || ""} placeholder="Cth: Bpk Budi (0812-3456-7890)" className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1">
                  <label className="text-sm font-medium">Sales Incharge (PIC)</label>
                  <input type="text" name="sales_rep" defaultValue={motor.sales_rep || ""} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm" />
                </div>
                <div className="space-y-1 sm:col-span-2">
                  <label className="text-sm font-medium">Catatan Internal / Rahasia</label>
                  <textarea name="internal_notes" defaultValue={motor.internal_notes || ""} rows={2} className="w-full px-3 py-2 rounded-lg border border-[var(--border)] focus:outline-none focus:border-[var(--primary)] text-sm resize-none"></textarea>
                </div>
              </div>
            </div>

            {userRole !== "MECHANIC" && (
              <div className="flex flex-col sm:flex-row justify-between items-center gap-4 bg-gray-50 p-4 rounded-xl border border-[var(--border)]">
                <div className="text-sm text-[var(--muted-foreground)]">
                  Langkah {visibleTabs.findIndex(t => t.id === activeTab) + 1} dari {visibleTabs.length}
                </div>
                <div className="flex gap-3 w-full sm:w-auto">
                  {visibleTabs.findIndex(t => t.id === activeTab) < visibleTabs.length - 1 ? (
                    <button 
                      type="button"
                      onClick={() => {
                        const idx = visibleTabs.findIndex(t => t.id === activeTab);
                        if (idx >= 0 && idx < visibleTabs.length - 1) setActiveTab(visibleTabs[idx + 1].id);
                      }}
                      className="flex-1 sm:flex-none px-6 py-2.5 rounded-lg border border-[var(--border)] bg-white font-bold hover:bg-gray-100 transition-colors flex items-center justify-center gap-2"
                    >
                      Selanjutnya <ChevronRight size={18} />
                    </button>
                  ) : (
                    <SubmitButton />
                  )}
                </div>
              </div>
            )}

          </form>
        </div>
      </div>

      {selectedImage && (
        <div 
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/90 backdrop-blur-sm p-4"
          onClick={() => setSelectedImage(null)}
        >
          <img src={selectedImage} alt="Preview" className="max-w-full max-h-full object-contain rounded-lg shadow-2xl" />
          <button className="absolute top-4 right-4 p-2 bg-white/10 text-white rounded-full hover:bg-white/20" onClick={() => setSelectedImage(null)}><X size={24} /></button>
        </div>
      )}
    </div>
  );
}
